# Generated by Django 6.0.3 on 2026-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
